[container]
[[container.additional_mounts]]
destination = '/Users/daonb/src/langchaingo'
source = '/Users/daonb/src/langchaingo'

[llm]
model = 'claude-sonnet-4-5-20250929'
provider = 'anthropic'
# provider = "ollama"
# model = "gemma3:1b"
