[llm]
# provider = "ollama"
# model = "gemma3:1b"
provider = "anthropic"
model = "claude-sonnet-4-20250514"
[[container.additional_mounts]]
source = "/Users/daonb/src/langchaingo"
destination = "/Users/daonb/src/langchaingo"
