[container]
[[container.additional_mounts]]
destination = '/Users/daonb/src/langchaingo'
source = '/Users/daonb/src/langchaingo'

[llm]
model = 'claude-sonnet-4-5-20250929'
provider = 'anthropic'

[run_in_shell]
run_on_host = ['^gh\s.*']
